version: '3.9'

services:
  terra:
    container_name: terra
    build: 
      context: .
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./src:/infra
    working_dir: /infra
